name: Build packer template

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.pkr.hcl'

jobs:
  build:
    name: Build Packer Templates
    uses: eingram-homelab/reusable_workflows/.github/workflows/packer-build.yaml@main
    secrets:
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}