name: Packer Validation

on:
  push:
    branches: [ develop ]
    paths:
      - '**.pkr.hcl'
  pull_request:
    branches: [ develop ]
    paths:
      - '**.pkr.hcl'

jobs:
  validate:
    name: Validate Packer Templates
    runs-on: arc-runners
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "latest"

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46.0.2
        with:
          files: |
            **/*.pkr.hcl

      - name: pause
        run: sleep 99999
        
      - name: Check Format for changed files
        if: steps.changed-files.outputs.all_changed_files != ''
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "Checking format for $file"
            dir=$(dirname "$file")
            packer fmt -check "$file"
          done
        
      - name: Validate Changed Templates
        if: steps.changed-files.outputs.all_changed_files != ''
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ "$file" == *.pkr.hcl || "$file" == *.json ]]; then
              echo "Validating $file"
              packer validate "$file"
            fi
          done
