name: Test passing info between workflows

on:
  workflow_dispatch:

jobs:
  test_set_var:
    name: Set and pass variable between workflows
    runs-on: arc-runners
    steps:
      - name: Set output variable
        id: set_output
        run: |
          echo "output_var=Hello from the first workflow" >> $GITHUB_OUTPUT

  call_workflow:
    needs: test_set_var
    uses: eingram-homelab/terraform/.github/workflows/test_reusable.yaml@main
    with:
      input_var: ${{ needs.test_set_var.outputs.output_var }}
