name: Test passing info between workflows

on:
  workflow_dispatch:

jobs:
  test_set_var:
    name: Set and pass variable between workflows
    runs-on: arc-runners
    steps:
      - name: Set test variable
        id: set_test_var
        run: |
          echo "test_var=Hello from the first workflow" >> $GITHUB_ENV

      - name: Print test variable
        run: |
          echo "Test variable set in the first step: ${{ env.test_var }}"

  call_workflow:
    needs: test_set_var
    uses: eingram-homelab/terraform/.github/workflows/test_reusable.yaml@main
    with:
      input_var: ${{ needs.test_set_var.env.test_var }}
