name: Validate packer templates

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.pkr.hcl'
  workflow_dispatch:

jobs:
  validate:
    name: Validate Packer Template
    uses: eingram-homelab/reusable_workflows/.github/workflows/packer_validate.yaml@main
    secrets:
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
