name: Validate packer templates

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.pkr.hcl'
  workflow_dispatch:

jobs:
  validate:
    uses: eingram-homelab/reusable_workflows/.github/workflows/packer_validate.yaml@main
    name: Validate Packer Template
    secrets: inherit