name: Packer Validation

on:
  push:
    branches: [ develop ]
    paths:
      - '**.pkr.hcl'
  pull_request:
    branches: [ develop ]
    paths:
      - '**.pkr.hcl'

jobs:
  validate:
    name: Validate Packer Templates
    runs-on: arc-runners
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "latest"

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46.0.2
        with:
          files: |
            **/*.pkr.hcl

      - name: Check Format for changed files
        if: steps.changed-files.outputs.all_changed_files != ''
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "Checking format for $file"
            packer fmt -check "$file"
          done
      
      - name: Run packer init
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "Running packer init for $file"
            packer init "$file"
          done 

      - name: Validate Changed Templates
        if: steps.changed-files.outputs.all_changed_files != ''
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "Validating $file"
            packer validate "$file"
          done
